# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronkit < Formula
  desc "Make cron human again - CLI tool for cron job management"
  homepage "https://github.com/hzerrad/cronkit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_amd64.tar.gz"
      sha256 "904213fb26bb80066171fcbf61ba9a1fcc66f207354ec402e74dcacb95f8db7a"

      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_darwin_arm64.tar.gz"
      sha256 "c4259ca1d5bb8e0462b77f7c74d49ebb21710e442b6fd911a29fd9c8523b731d"

      def install
        bin.install "cronkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_amd64.tar.gz"
      sha256 "2eb8dec964efd56bdbef8d10e716253d2f78be115220b5e3ad6075bab5c74d13"
      def install
        bin.install "cronkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hzerrad/cronkit/releases/download/v0.1.0/cronkit_linux_arm64.tar.gz"
      sha256 "97b91158d33a5f4c5caa89ca15ff3417999769702d324e8bb4cd6bee7cf8c600"
      def install
        bin.install "cronkit"
      end
    end
  end

  test do
    system "#{bin}/cronkit", "version"
  end
end
